### ISSUE TITLE
VSCode cannot connect?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/vscode-flix#304]
When using the newest VSCode I get:

```
Listen on 'localhost/127.0.0.1:8888'.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED ::1:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Emitted 'error' event on Ye instance at:
    at sm (c:\Users\iostream\.vscode\extensions\flix.flix-1.10.0\server\out\server.js:75:45285)
    at ClientRequest.<anonymous> (c:\Users\iostream\.vscode\extensions\flix.flix-1.10.0\server\out\server.js:75:43590)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8888
}

Node.js v18.15.0
[Info  - 1:13:22 PM] Connection to server got closed. Server will restart.
```

(I have a suspicion that VSCode changed something and not us....)

**Comment by magnus-madsen** [comment]
@sockmaster27 @jaschdoc @mlutze @JonathanStarup This is pretty urgent since everything is broken in VSCode. If or when you have time, please have a look.

I suspect they changed something which broke something in our code.

Probably the starting point for us is in `Socket.ts`.

**Comment by magnus-madsen** [comment]
wscat suggests that the Flix compiler (java process) starts correctly and is listening for a bit.

**Comment by magnus-madsen** [comment]
It seems that the VSCode extesion, for unknown reasons, is blocked from connecting to the local port.

**Comment by magnus-madsen** [comment]
https://github.com/microsoft/vscode/issues/192545

**Comment by magnus-madsen** [comment]
Deplying a fix. Apparently using "localhost" no longer works.

**Comment by magnus-madsen** [comment]
Phew. Fixed.
